Environment:
  ep_length: 1  # episode length

  sections:
    - capacity: 5
      num_type0_agents: 0
      num_type1_agents: 0
    - capacity: 5
      num_type0_agents: 35
      num_type1_agents: 15
    - capacity: 5
      num_type0_agents: 0
      num_type1_agents: 0
    - capacity: 5
      num_type0_agents: 35
      num_type1_agents: 15
    - capacity: 5
      num_type0_agents: 0
      num_type1_agents: 0
