Environment:
  ep_length: 1  # episode length

  sections:
    - capacity: 3
      num_type0_agents: 0
      num_type1_agents: 0
    - capacity: 3
      num_type0_agents: 17
      num_type1_agents: 7
    - capacity: 3
      num_type0_agents: 0
      num_type1_agents: 0
    - capacity: 3
      num_type0_agents: 18
      num_type1_agents: 8
    - capacity: 3
      num_type0_agents: 0
      num_type1_agents: 0
